-- Archivo principal del proyecto Grupo 34
-- Autor: Grupo 34
-- Contenedor: XEPDB1
-- Usuario: coffeewild

-- En este archivo se colocará:
-- 1. Definición de tablas
-- 2. Funciones
-- 3. Procedimientos almacenados
-- 4. Triggers
-- 5. Vistas de reporte (10 vistas)
-- 6. Inserts de prueba
